language: java
jdk:
  - openjdk11
script: "mvn -P codecoverage clean test sonar:sonar"
after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "hhru"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
